package com.jobs.domain;
// Generated Apr 20, 2018 10:30:10 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Jobs generated by hbm2java
 */
public class Jobs implements java.io.Serializable {

    private Long jobId;
    private String jobIdEnc;
    private String trackingNo;
    private String jobNo;
    private String icNo;
    private Date loadingDate;
    private String barcode;
    private String indenter;
    private String phone;
    private String project;
    private String subSystem;
    private String circuitName;
    private String model;
    private String remark;
    private Date addedDate;
    private Date updateDate;
    private Integer addedBy;
    private String addedByName;
    private Boolean status;
    private Boolean deleteStatus;

    public Jobs() {
    }

    public Jobs(Long jobId, String trackingNo, String jobNo, String icNo, Date loadingDate, String barcode) {
        this.jobId = jobId;
        this.trackingNo = trackingNo;
        this.jobNo = jobNo;
        this.icNo = icNo;
        this.loadingDate = loadingDate;
        this.barcode = barcode;
    }

    public Jobs(Long jobId, String trackingNo, String jobNo, String icNo, Date loadingDate, String barcode, String indenter, String phone, String project, String subSystem, String circuitName, String model, String remark, Date addedDate, Integer addedBy, String addedByName, Boolean status, Boolean deleteStatus) {
        this.jobId = jobId;
        this.trackingNo = trackingNo;
        this.jobNo = jobNo;
        this.icNo = icNo;
        this.loadingDate = loadingDate;
        this.barcode = barcode;
        this.indenter = indenter;
        this.phone = phone;
        this.project = project;
        this.subSystem = subSystem;
        this.circuitName = circuitName;
        this.model = model;
        this.remark = remark;
        this.addedDate = addedDate;
        this.addedBy = addedBy;
        this.addedByName = addedByName;
        this.status = status;
        this.deleteStatus = deleteStatus;
    }

    public Long getJobId() {
        return this.jobId;
    }

    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    public String getJobIdEnc() {
        return jobIdEnc;
    }

    public void setJobIdEnc(String jobIdEnc) {
        this.jobIdEnc = jobIdEnc;
    }

    public String getTrackingNo() {
        return this.trackingNo;
    }

    public void setTrackingNo(String trackingNo) {
        this.trackingNo = trackingNo;
    }

    public String getJobNo() {
        return this.jobNo;
    }

    public void setJobNo(String jobNo) {
        this.jobNo = jobNo;
    }

    public String getIcNo() {
        return this.icNo;
    }

    public void setIcNo(String icNo) {
        this.icNo = icNo;
    }

    public Date getLoadingDate() {
        return this.loadingDate;
    }

    public void setLoadingDate(Date loadingDate) {
        this.loadingDate = loadingDate;
    }

    public String getBarcode() {
        return this.barcode;
    }

    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    public String getIndenter() {
        return this.indenter;
    }

    public void setIndenter(String indenter) {
        this.indenter = indenter;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getProject() {
        return this.project;
    }

    public void setProject(String project) {
        this.project = project;
    }

    public String getSubSystem() {
        return this.subSystem;
    }

    public void setSubSystem(String subSystem) {
        this.subSystem = subSystem;
    }

    public String getCircuitName() {
        return this.circuitName;
    }

    public void setCircuitName(String circuitName) {
        this.circuitName = circuitName;
    }

    public String getModel() {
        return this.model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Date getAddedDate() {
        return this.addedDate;
    }

    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }

    public Integer getAddedBy() {
        return this.addedBy;
    }

    public Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    public void setAddedBy(Integer addedBy) {
        this.addedBy = addedBy;
    }

    public String getAddedByName() {
        return this.addedByName;
    }

    public void setAddedByName(String addedByName) {
        this.addedByName = addedByName;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public Boolean getDeleteStatus() {
        return this.deleteStatus;
    }

    public void setDeleteStatus(Boolean deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

}
